# Generated by Django 2.2.23 on 2021-09-28 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("review", "0001_initial")
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="GPA",
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='GPA')
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(null=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')
        )
    ]